const express = require("express"); const helmet = require("helmet"); const { z } = require("zod");
const { getConfig, createPool, createLogger, withTransaction, requestContext, sendOk, sendError, verifyAccessToken, publishOutboxEvent, writeAudit } = require("@wallet/common");
const repo = require("./repository"); const { defaultProviders, CircuitBreaker } = require("./providers");
const schema = z.object({ provider_type: z.enum(["wallet_funding","bank_withdrawal","bill_payment","airtime"]), provider_name: z.string().min(2), transaction_request_id: z.string().uuid().optional(), internal_reference: z.string().min(3), amount_minor: z.number().int().positive(), currency: z.string().length(3), payload: z.record(z.any()).optional() });
function auth(config) { return (req, res, next) => { const value = req.get("authorization") || ""; try { const token = value.startsWith("Bearer ") ? value.slice(7) : ""; req.actor = verifyAccessToken(config, token); next(); } catch (_e) { return sendError(res, 401, "UNAUTHORIZED", "Valid bearer token required"); } }; }
function createApp(deps = {}) {
  const config = deps.config || getConfig("payment-integration-service"); const pool = deps.pool || createPool(config); const logger = deps.logger || createLogger("payment-integration-service"); const providers = deps.providers || defaultProviders(); const breakers = new Map(); const app = express();
  app.use(helmet()); app.use(express.json({ limit: "256kb" })); app.use(requestContext);
  const breakerFor = (name) => { if (!breakers.has(name)) breakers.set(name, new CircuitBreaker({ failureThreshold: config.providerFailureThreshold || 3, resetTimeoutMs: config.providerCircuitResetMs || 30000 })); return breakers.get(name); };
  async function callWithRetry(provider, operation, input) { const breaker = breakerFor(provider.name); if (!breaker.allow()) throw Object.assign(new Error("Provider circuit is open"), { code: "PROVIDER_CIRCUIT_OPEN", retryable: true }); let last; for (let attempt = 0; attempt < (config.providerMaxAttempts || 3); attempt += 1) { try { const result = await Promise.race([operation(input), new Promise((_, reject) => setTimeout(() => reject(Object.assign(new Error("Provider timeout"), { code: "PROVIDER_TIMEOUT", retryable: true })), config.providerTimeoutMs || 5000))]); breaker.success(); return result; } catch (error) { last = error; breaker.failure(); if (!error.retryable || attempt === (config.providerMaxAttempts || 3) - 1) break; await new Promise((resolve) => setTimeout(resolve, Math.min(1000 * (2 ** attempt), 5000))); } } throw last; }
  app.get("/health/live", (_q, r) => r.json({ status: "ok" })); app.get("/health/ready", async (_q, r) => { try { await pool.query("SELECT 1"); r.json({ status: "ready" }); } catch (_e) { r.status(503).json({ status: "not_ready" }); } });
  app.post("/payments/initiate", auth(config), async (req, res) => { const parsed = schema.safeParse(req.body); if (!parsed.success) return sendError(res, 400, "VALIDATION_ERROR", "Invalid provider request"); const key = req.get("Idempotency-Key"); if (!key || key.length < 8) return sendError(res, 400, "IDEMPOTENCY_KEY_REQUIRED", "Idempotency-Key is required"); const provider = providers[parsed.data.provider_name]; if (!provider || provider.type !== parsed.data.provider_type) return sendError(res, 400, "PROVIDER_NOT_FOUND", "Unsupported provider"); try { const result = await withTransaction(pool, async (client) => { const created = await repo.createAttempt(client, { ...parsed.data, idempotency_key: key }, provider.name); if (created.repeated) return created.attempt; const response = await callWithRetry(provider, (input) => provider.initiate(input), { ...parsed.data, internal_reference: created.attempt.internal_reference }); const normalized = provider.normalize(response); const attempt = await repo.updateAttempt(client, created.attempt.id, { status: normalized.normalized_status === "successful" ? "successful" : "pending", normalized_status: normalized.normalized_status, provider_reference: normalized.provider_reference, response_code: normalized.response_code, response_hash: require("crypto").createHash("sha256").update(JSON.stringify(response)).digest("hex") }); await publishOutboxEvent(client, { event_type: "payment.provider.status.changed", producer: "payment-integration-service", correlation_id: req.correlationId, payload: { provider_name: provider.name, provider_reference: attempt.provider_reference, normalized_status: attempt.normalized_status, transaction_request_id: attempt.transaction_request_id } }); await writeAudit(client, { actor_type: "system", action: "payment.provider.initiated", resource_type: "provider_attempt", resource_id: attempt.id, result: "success", correlation_id: req.correlationId, request_id: req.requestId, metadata: { provider_name: provider.name, provider_type: provider.type, normalized_status: attempt.normalized_status } }); return { attempt, provider_response: normalized }; }); return sendOk(res, result, 201); } catch (error) { logger.warn({ err: error, request_id: req.requestId }, "provider initiation failed"); return sendError(res, error.code === "IDEMPOTENCY_CONFLICT" ? 409 : 502, error.code || "PROVIDER_REQUEST_FAILED", "Provider request could not be completed safely"); } });
  app.post("/payments/verify", auth(config), async (req, res) => { const input = z.object({ provider_name: z.string(), provider_reference: z.string() }).safeParse(req.body); if (!input.success) return sendError(res, 400, "VALIDATION_ERROR", "Invalid verification request"); const provider = providers[input.data.provider_name]; if (!provider) return sendError(res, 404, "PROVIDER_NOT_FOUND", "Unsupported provider"); try { const response = await callWithRetry(provider, (reference) => provider.verify(reference), input.data.provider_reference); return sendOk(res, { provider_name: provider.name, provider_reference: input.data.provider_reference, ...provider.normalize(response) }); } catch (error) { return sendError(res, 502, error.code || "PROVIDER_VERIFY_FAILED", "Provider verification failed"); } });
  app.get("/providers/:provider/status/:reference", auth(config), async (req, res) => { const provider = providers[req.params.provider]; if (!provider) return sendError(res, 404, "PROVIDER_NOT_FOUND", "Unsupported provider"); try { const response = await callWithRetry(provider, (reference) => provider.verify(reference), req.params.reference); return sendOk(res, { provider_name: provider.name, provider_reference: req.params.reference, ...provider.normalize(response) }); } catch (error) { return sendError(res, 502, error.code || "PROVIDER_STATUS_FAILED", "Provider status unavailable"); } });
  app.post("/providers/:provider/callbacks", async (req, res) => { const provider = providers[req.params.provider]; if (!provider) return sendError(res, 404, "PROVIDER_NOT_FOUND", "Unsupported provider"); const signature = req.get("X-Provider-Signature"); if (!provider.verifySignature(req.body, signature, config.providerWebhookSecret)) return sendError(res, 401, "INVALID_CALLBACK_SIGNATURE", "Callback signature is invalid"); const normalized = provider.normalize(req.body); if (!normalized.provider_reference) return sendError(res, 400, "INVALID_CALLBACK", "Provider reference is required"); try { const result = await withTransaction(pool, async (client) => { const saved = await repo.saveCallback(client, { provider_name: provider.name, provider_reference: normalized.provider_reference, callback_id: req.body.callback_id, event_type: req.body.event_type || "status", normalized_status: normalized.normalized_status, payload: req.body }); await publishOutboxEvent(client, { event_type: saved.duplicate ? "payment.provider.callback.duplicate" : "payment.provider.callback.received", producer: "payment-integration-service", correlation_id: req.correlationId, payload: { provider_name: provider.name, provider_reference: normalized.provider_reference, normalized_status: normalized.normalized_status, duplicate: saved.duplicate } }); return saved; }); return sendOk(res, result); } catch (error) { return sendError(res, 422, error.code || "CALLBACK_FAILED", "Callback could not be recorded"); } });
  return { app, pool, providers, breakers };
}
module.exports = { createApp, schema };
