function reconcileRecords(providerRecords, internalTransactions, ledgerPostings, pendingThresholdMs = 86400000, now = new Date()) {
  const exceptions = []; const byProvider = new Map(); providerRecords.forEach((record) => { const list = byProvider.get(record.provider_reference) || []; list.push(record); byProvider.set(record.provider_reference, list); });
  for (const [reference, records] of byProvider) if (records.length > 1) exceptions.push({ exception_type: "duplicate_provider_reference", provider_reference: reference, severity: "high", evidence: { count: records.length } });
  const internalByRef = new Map(internalTransactions.map((item) => [item.transaction_reference, item])); const ledgerByRef = new Map(ledgerPostings.map((item) => [item.transaction_reference, item]));
  for (const record of providerRecords) { const internal = internalByRef.get(record.transaction_reference); if (!internal) { exceptions.push({ exception_type: "missing_internal_record", provider_reference: record.provider_reference, transaction_reference: record.transaction_reference, amount_minor: record.amount_minor, currency: record.currency, severity: "high" }); continue; } if (Number(internal.amount_minor) !== Number(record.amount_minor)) exceptions.push({ exception_type: "amount_mismatch", provider_reference: record.provider_reference, transaction_reference: internal.transaction_reference, amount_minor: record.amount_minor, currency: record.currency, severity: "high", evidence: { internal_amount_minor: internal.amount_minor } }); const ledger = ledgerByRef.get(internal.transaction_reference); if (!ledger) exceptions.push({ exception_type: "missing_internal_record", provider_reference: record.provider_reference, transaction_reference: internal.transaction_reference, severity: "critical", evidence: { reason: "ledger_posting_missing" } }); else if (Number(ledger.amount_minor) !== Number(record.amount_minor)) exceptions.push({ exception_type: "amount_mismatch", provider_reference: record.provider_reference, transaction_reference: internal.transaction_reference, severity: "critical", evidence: { ledger_amount_minor: ledger.amount_minor, provider_amount_minor: record.amount_minor } }); }
  for (const internal of internalTransactions) { if (internal.status === "successful" && internal.provider_reference && !providerRecords.some((record) => record.provider_reference === internal.provider_reference)) exceptions.push({ exception_type: "missing_provider_record", provider_reference: internal.provider_reference, transaction_reference: internal.transaction_reference, severity: "high" }); if (["pending_provider", "pending"].includes(internal.status) && now - new Date(internal.updated_at || internal.created_at) > pendingThresholdMs) exceptions.push({ exception_type: "late_callback", transaction_reference: internal.transaction_reference, severity: "medium" }); }
  return exceptions;
}
module.exports = { reconcileRecords };
