const { randomUUID } = require("crypto"); const { writeAudit, publishOutboxEvent } = require("@wallet/common");
async function createBatch(client, input, actorId) { const result = await client.query(`INSERT INTO reconciliation.reconciliation_batches(id,provider_name,batch_type,settlement_date,source_file_checksum,status,started_at,metadata) VALUES ($1,$2,$3,$4,$5,'processing',now(),$6) RETURNING *`, [randomUUID(), input.provider_name, input.batch_type || "settlement", input.settlement_date, input.source_file_checksum, input.metadata || {}]); await writeAudit(client,{actor_type:"admin",actor_id:actorId,action:"reconciliation.batch.created",resource_type:"reconciliation_batch",resource_id:result.rows[0].id,result:"success",correlation_id:input.correlation_id,metadata:{provider_name:input.provider_name,batch_type:input.batch_type}}); return result.rows[0]; }
async function insertRecords(client, batchId, providerName, records) { const saved=[]; for(const record of records){const result=await client.query(`INSERT INTO reconciliation.provider_records(reconciliation_batch_id,provider_name,provider_reference,transaction_reference,amount_minor,currency,provider_status,occurred_at,raw_record) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT DO NOTHING RETURNING *`,[batchId,providerName,record.provider_reference,record.transaction_reference,record.amount_minor,record.currency,record.provider_status,record.occurred_at,record.raw_record]); if(result.rows[0])saved.push(result.rows[0]);} return saved; }
async function loadInternal(client, providerName, from, to) { const transactions=await client.query(`SELECT * FROM transactions.transaction_requests WHERE ($1::date IS NULL OR created_at >= $1::date) AND ($2::date IS NULL OR created_at < ($2::date + interval '1 day')) AND transaction_type IN ('wallet_funding','bank_withdrawal','bill_payment','airtime_purchase')`,[from||null,to||null]); const refs=transactions.rows.map((item)=>item.transaction_reference); if(!refs.length)return{transactions:[],ledger:[]}; const ledger=await client.query("SELECT transaction_reference, SUM(amount_minor)::bigint AS amount_minor, currency FROM ledger.ledger_entries e JOIN ledger.ledger_transactions t ON t.id=e.ledger_transaction_id WHERE t.transaction_reference = ANY($1) GROUP BY transaction_reference,currency",[refs]); return{transactions:transactions.rows,ledger:ledger.rows}; }
async function addExceptions(client,batchId,exceptions){for(const item of exceptions)await client.query(`INSERT INTO reconciliation.reconciliation_items(reconciliation_batch_id,provider_record_id,provider_reference,transaction_reference,amount_minor,currency,match_status,exception_type,resolution_status,severity,evidence) VALUES ($1,$2,$3,$4,$5,$6,'exception',$7,'open',$8,$9)`,[batchId,item.provider_record_id||null,item.provider_reference||null,item.transaction_reference||null,item.amount_minor||null,item.currency||null,item.exception_type,item.severity||"medium",item.evidence||{}]);}
async function finishBatch(client,batchId,exceptionCount,reportCsv){return (await client.query("UPDATE reconciliation.reconciliation_batches SET status=$2,completed_at=now(),exception_count=$3,report_csv=$4 WHERE id=$1 RETURNING *",[batchId,exceptionCount?"partial":"completed",exceptionCount,reportCsv||null])).rows[0];}
async function getBatch(client,id){return (await client.query("SELECT * FROM reconciliation.reconciliation_batches WHERE id=$1",[id])).rows[0]||null;}
async function listExceptions(client,batchId){return (await client.query("SELECT * FROM reconciliation.reconciliation_items WHERE reconciliation_batch_id=$1 ORDER BY created_at",[batchId])).rows;}
module.exports={createBatch,insertRecords,loadInternal,addExceptions,finishBatch,getBatch,listExceptions};
