FROM node:20-alpine
ARG SERVICE
WORKDIR /app
COPY package*.json ./
COPY packages ./packages
COPY services/${SERVICE} ./services/${SERVICE}
RUN npm ci --omit=dev
ENV NODE_ENV=production
CMD ["sh", "-c", "npm --workspace services/${SERVICE} start"]
