const express = require("express");
const helmet = require("helmet");
const { z } = require("zod");
const { getConfig, createPool, createLogger, withTransaction, requestContext, sendOk, sendError, verifyAccessToken, publishOutboxEvent, writeAudit } = require("@wallet/common");
const repo = require("./repository");
const { createClients } = require("./clients");

const base = z.object({ user_id: z.string().uuid().optional(), kyc_tier: z.enum(["tier_0","tier_1","tier_2","tier_3"]).optional(), source_wallet_id: z.string().uuid().optional(), destination_wallet_id: z.string().uuid().optional(), amount_minor: z.number().int().positive().max(Number.MAX_SAFE_INTEGER), currency: z.string().length(3).transform((x) => x.toUpperCase()), channel: z.string().min(1).default("mobile"), narration: z.string().max(200).optional(), metadata: z.record(z.any()).optional() });
const transferSchema = base.extend({ source_wallet_id: z.string().uuid(), destination_wallet_id: z.string().uuid(), pin: z.string().min(4).max(6) });
const externalSchema = base.extend({ provider_name: z.string().min(2).default("mock"), provider_payload: z.record(z.any()).optional() });

function auth(config) { return (req, res, next) => { const value = req.get("authorization") || ""; try { const claims = verifyAccessToken(config, value.startsWith("Bearer ") ? value.slice(7) : ""); req.user = { id: claims.sub }; req.authorization = value; next(); } catch (_e) { return sendError(res, 401, "UNAUTHORIZED", "Valid bearer token required"); } }; }
function idempotency(req, res) { const key = req.get("Idempotency-Key"); if (!key || key.length < 8) { sendError(res, 400, "IDEMPOTENCY_KEY_REQUIRED", "Idempotency-Key is required"); return null; } return key; }

function createApp(deps = {}) {
  const config = deps.config || getConfig("transaction-service"); const pool = deps.pool || createPool(config); const logger = deps.logger || createLogger("transaction-service"); const clients = createClients(config, deps.clients); const app = express();
  app.use(helmet()); app.use(express.json({ limit: "256kb" })); app.use(requestContext);
  app.get("/health/live", (_req, res) => res.json({ status: "ok" }));
  app.get("/health/ready", async (_req, res) => { try { await pool.query("SELECT 1"); res.json({ status: "ready" }); } catch (_e) { res.status(503).json({ status: "not_ready" }); } });

  async function runTransfer(req, res) {
    const parsed = transferSchema.safeParse({ ...req.body, user_id: req.user.id }); if (!parsed.success) return sendError(res, 400, "VALIDATION_ERROR", "Invalid transfer payload"); const key = idempotency(req, res); if (!key) return;
    try {
      const result = await withTransaction(pool, async (client) => {
        const created = await repo.create(client, { ...parsed.data, transaction_type: "wallet_transfer" }, key); if (created.repeated) return created.transaction;
        const tx = created.transaction;
        await repo.transition(client, tx.id, "pending_validation");
        const source = await clients.wallet(parsed.data.source_wallet_id, req.authorization); const destination = await clients.wallet(parsed.data.destination_wallet_id, req.authorization);
        if (!source || !destination || source.status !== "active" || destination.status !== "active" || source.currency !== parsed.data.currency || destination.currency !== parsed.data.currency) { await repo.transition(client, tx.id, "failed", { failure_code: "WALLET_INVALID" }); throw Object.assign(new Error("Wallet is invalid or inactive"), { code: "WALLET_INVALID" }); }
        await clients.pin(req.authorization, parsed.data.pin);
        await repo.transition(client, tx.id, "pending_fraud_check");
        const limit = await clients.limits({ user_id: req.user.id, kyc_tier: parsed.data.kyc_tier || "tier_0", transaction_reference: tx.transaction_reference, transaction_type: "wallet_transfer", channel: parsed.data.channel, amount_minor: parsed.data.amount_minor, currency: parsed.data.currency }, req.authorization, `${key}:limit`);
        if (!limit.reservation) { await repo.transition(client, tx.id, "failed", { failure_code: "LIMIT_EXCEEDED" }); throw Object.assign(new Error("Transaction limit exceeded"), { code: "LIMIT_EXCEEDED" }); }
        const fee = await clients.fee({ user_id: req.user.id, transaction_reference: tx.transaction_reference, transaction_type: "wallet_transfer", channel: parsed.data.channel, amount_minor: parsed.data.amount_minor, currency: parsed.data.currency }, req.authorization, `${key}:fee`);
        const fraud = await clients.fraud({ evaluation_type: "transaction", user_id: req.user.id, transaction_reference: tx.transaction_reference, amount_minor: parsed.data.amount_minor, currency: parsed.data.currency, new_device: parsed.data.metadata?.new_device === true, suspicious_ip: parsed.data.metadata?.suspicious_ip === true }, req.authorization, `${key}:fraud`);
        if (["block", "manual_review", "restrict_account"].includes(fraud.decision)) { await repo.transition(client, tx.id, fraud.decision === "manual_review" ? "under_review" : "failed", { failure_code: `FRAUD_${fraud.decision.toUpperCase()}`, fraud_decision_id: fraud.id }); await clients.limitRelease(limit.reservation.reservation_reference, req.authorization); return { ...tx, status: fraud.decision === "manual_review" ? "under_review" : "failed", fraud_decision: fraud }; }
        const total = parsed.data.amount_minor + Number(fee.fee_minor || 0); const entries = [{ account_id: source.ledger_account_id, entry_type: "debit", amount_minor: total, currency: parsed.data.currency }, { account_id: destination.ledger_account_id, entry_type: "credit", amount_minor: parsed.data.amount_minor, currency: parsed.data.currency }]; if (Number(fee.fee_minor || 0) > 0) entries.push({ account_id: fee.revenue_account_id || fee.ledger_posting_instruction?.credit_account_id, entry_type: "credit", amount_minor: Number(fee.fee_minor), currency: parsed.data.currency });
        const ledger = await clients.ledger({ transaction_request_id: tx.id, ledger_reference: `LED-${tx.transaction_reference}`, transaction_reference: tx.transaction_reference, transaction_type: "transfer", currency: parsed.data.currency, description: parsed.data.narration, entries }, `${key}:ledger`);
        const final = await repo.transition(client, tx.id, "successful", { ledger_reference: ledger.ledger_reference, limit_reservation_reference: limit.reservation.reservation_reference, fee_quote_reference: fee.quote_reference, fraud_decision_id: fraud.id }); await clients.limitCommit(limit.reservation.reservation_reference, req.authorization); await publishOutboxEvent(client, { event_type: "transaction.successful", producer: "transaction-service", correlation_id: req.correlationId, payload: { transaction_id: final.id, transaction_reference: final.transaction_reference, user_id: final.user_id, amount_minor: final.amount_minor, currency: final.currency, ledger_reference: final.ledger_reference } }); await writeAudit(client, { actor_type: "user", actor_id: req.user.id, action: "transaction.successful", resource_type: "transaction", resource_id: final.id, result: "success", correlation_id: req.correlationId, request_id: req.requestId }); return final;
      }); return sendOk(res, result, result.status === "initiated" ? 201 : 200);
    } catch (error) { logger.warn({ err: error, request_id: req.requestId }, "transfer failed"); return sendError(res, error.code === "IDEMPOTENCY_CONFLICT" ? 409 : 422, error.code || "TRANSFER_FAILED", error.message); }
  }

  app.post("/transactions/transfers", auth(config), runTransfer);

  async function initiateExternal(type, req, res) { const parsed = externalSchema.safeParse({ ...req.body, user_id: req.user.id }); if (!parsed.success) return sendError(res, 400, "VALIDATION_ERROR", "Invalid transaction payload"); const key = idempotency(req, res); if (!key) return; try { const result = await withTransaction(pool, async (client) => { const created = await repo.create(client, { ...parsed.data, transaction_type: type }, key); if (created.repeated) return created.transaction; await repo.transition(client, created.transaction.id, "pending_validation"); const providerReference = `${created.transaction.transaction_reference}-${parsed.data.provider_name}`; await repo.saveProviderRequest(client, created.transaction.id, parsed.data.provider_name, type, providerReference); return repo.transition(client, created.transaction.id, "pending_provider", { provider_name: parsed.data.provider_name, provider_reference: providerReference }); }); return sendOk(res, result, 201); } catch (error) { return sendError(res, error.code === "IDEMPOTENCY_CONFLICT" ? 409 : 422, error.code || "TRANSACTION_INITIATION_FAILED", error.message); } }
  app.post("/transactions/fund-wallet", auth(config), (req, res) => initiateExternal("wallet_funding", req, res)); app.post("/transactions/withdrawals", auth(config), (req, res) => initiateExternal("bank_withdrawal", req, res)); app.post("/transactions/bills", auth(config), (req, res) => initiateExternal("bill_payment", req, res)); app.post("/transactions/airtime", auth(config), (req, res) => initiateExternal("airtime_purchase", req, res));
  app.get("/transactions", auth(config), async (req, res) => sendOk(res, { transactions: await repo.history(pool, req.user.id, Number(req.query.limit || 50), Number(req.query.offset || 0)) })); app.get("/transactions/:id", auth(config), async (req, res) => { const tx = await repo.get(pool, req.params.id); return tx && tx.user_id === req.user.id ? sendOk(res, tx) : sendError(res, 404, "TRANSACTION_NOT_FOUND", "Transaction not found"); });
  app.post("/transactions/:id/reverse", auth(config), async (req, res) => { const key = idempotency(req, res); if (!key) return; try { const result = await withTransaction(pool, async (client) => { const tx = await repo.get(client, req.params.id); if (!tx || tx.user_id !== req.user.id) return null; if (tx.status !== "successful" || !tx.ledger_reference) throw Object.assign(new Error("Only successful ledger-posted transactions can be reversed"), { code: "REVERSAL_NOT_ALLOWED" }); const reversal = await clients.ledgerReverse(tx.ledger_reference, key, req.body.reason || "Customer reversal request"); const updated = await repo.transition(client, tx.id, "reversed", { failure_reason: req.body.reason || "Customer reversal request" }); await publishOutboxEvent(client, { event_type: "transaction.reversed", producer: "transaction-service", correlation_id: req.correlationId, payload: { transaction_id: updated.id, transaction_reference: updated.transaction_reference, reversal_reference: reversal.ledger_reference } }); await writeAudit(client, { actor_type: "user", actor_id: req.user.id, action: "transaction.reversal.requested", resource_type: "transaction", resource_id: tx.id, result: "success", reason: req.body.reason, correlation_id: req.correlationId, request_id: req.requestId }); return updated; }); return result ? sendOk(res, result) : sendError(res, 404, "TRANSACTION_NOT_FOUND", "Transaction not found"); } catch (error) { return sendError(res, 422, error.code || "REVERSAL_FAILED", error.message); } });
  app.post("/providers/:provider/callbacks", async (req, res) => { const input = { provider_name: req.params.provider, provider_reference: req.body.provider_reference, provider_callback_id: req.body.provider_callback_id, event_type: req.body.event_type || "status", normalized_status: req.body.normalized_status, payload: req.body, signature_valid: req.body.signature_valid === true }; if (!input.signature_valid) return sendError(res, 401, "INVALID_CALLBACK_SIGNATURE", "Provider callback signature is invalid"); try { const result = await withTransaction(pool, async (client) => { const saved = await repo.callback(client, input); if (saved.duplicate) return saved; const txResult = await client.query("SELECT * FROM transactions.transaction_requests WHERE provider_reference=$1", [input.provider_reference]); if (txResult.rows[0] && input.normalized_status === "successful") await repo.transition(client, txResult.rows[0].id, "successful"); else if (txResult.rows[0] && input.normalized_status === "failed") await repo.transition(client, txResult.rows[0].id, "failed", { failure_code: "PROVIDER_FAILED" }); await publishOutboxEvent(client, { event_type: saved.duplicate ? "payment.provider.callback.duplicate" : "payment.provider.callback.received", producer: "transaction-service", correlation_id: req.correlationId, payload: { provider_name: input.provider_name, provider_reference: input.provider_reference, normalized_status: input.normalized_status } }); return saved; }); return sendOk(res, result); } catch (error) { return sendError(res, 422, error.code || "CALLBACK_FAILED", error.message); } });
  return { app, pool, clients };
}
module.exports = { createApp };
