const express=require("express");const helmet=require("helmet");const {z}=require("zod");
const {getConfig,createPool,createLogger,withTransaction,requestContext,sendOk,sendError,verifyAccessToken,publishOutboxEvent,writeAudit}=require("@wallet/common");
const repo=require("./repository");
const types=["wallet_transfer","withdrawal","bill_payment","airtime_purchase"];
const quoteSchema=z.object({user_id:z.string().uuid().optional(),transaction_reference:z.string().min(3).optional(),transaction_type:z.enum(types),channel:z.string().min(1),amount_minor:z.number().int().positive().max(Number.MAX_SAFE_INTEGER),currency:z.string().length(3).transform(v=>v.toUpperCase()),kyc_tier:z.enum(["tier_0","tier_1","tier_2","tier_3"]).optional(),metadata:z.record(z.any()).optional()});
const ruleSchema=z.object({fee_code:z.string().min(3),transaction_type:z.enum(types),channel:z.string().min(1),currency:z.string().length(3).transform(v=>v.toUpperCase()),fixed_amount_minor:z.number().int().nonnegative().optional(),percentage_bps:z.number().int().nonnegative().optional(),min_fee_minor:z.number().int().nonnegative().nullable().optional(),max_fee_minor:z.number().int().nonnegative().nullable().optional(),waived:z.boolean().optional(),waiver_conditions:z.record(z.any()).optional(),revenue_account_code:z.string().min(3).optional(),priority:z.number().int().optional(),metadata:z.record(z.any()).optional()}).refine(r=>(r.fixed_amount_minor||0)>0||(r.percentage_bps||0)>0||r.waived,"fee rule must calculate or waive a fee").refine(r=>r.max_fee_minor==null||r.min_fee_minor==null||r.max_fee_minor>=r.min_fee_minor,"max fee must be at least min fee");
const configSchema=z.object({description:z.string().min(3),reason:z.string().min(3),rules:z.array(ruleSchema).min(1)});
function bearer(config,role){return(req,res,next)=>{const value=req.get("authorization")||"";try{const claims=verifyAccessToken(config,value.startsWith("Bearer ")?value.slice(7):"");if(role&&!(claims.roles||[]).includes(role))return sendError(res,403,"FORBIDDEN",`Role ${role} is required`);req.actor={id:claims.sub,roles:claims.roles||[]};next();}catch(_e){return sendError(res,401,"UNAUTHORIZED","Valid bearer token required");}};}
function createApp(deps={}){const config=deps.config||getConfig("fee-service"),pool=deps.pool||createPool(config),logger=deps.logger||createLogger("fee-service"),app=express();app.use(helmet());app.use(express.json({limit:"256kb"}));app.use(requestContext);
  app.get("/health/live",(_q,r)=>r.json({status:"ok"}));app.get("/health/ready",async(_q,r)=>{try{await pool.query("SELECT 1");r.json({status:"ready"});}catch(_e){r.status(503).json({status:"not_ready"});}});
  const quoteHandler=async(req,res)=>{const parsed=quoteSchema.safeParse(req.body);if(!parsed.success)return sendError(res,400,"VALIDATION_ERROR","Invalid fee quote request");const key=req.get("Idempotency-Key");if(!key||key.length<8)return sendError(res,400,"IDEMPOTENCY_KEY_REQUIRED","Idempotency-Key is required");try{const value=await withTransaction(pool,async client=>{const result=await repo.quote(client,parsed.data,key,req.correlationId);if(!result.repeated){await publishOutboxEvent(client,{event_type:"fees.calculated",producer:"fee-service",correlation_id:req.correlationId,payload:{quote_reference:result.quote_reference,user_id:result.user_id,transaction_reference:result.transaction_reference,fee_minor:Number(result.fee_minor),currency:result.currency,fee_code:result.fee_code}});await writeAudit(client,{actor_type:"system",action:"fees.calculated",resource_type:"fee_quote",resource_id:result.id,result:"success",correlation_id:req.correlationId,request_id:req.requestId,metadata:{fee_code:result.fee_code,amount_minor:result.amount_minor,fee_minor:result.fee_minor,currency:result.currency,config_version:result.config_version}});}return result;});return sendOk(res,value,value.repeated?200:201);}catch(error){logger.warn({err:error,request_id:req.requestId},"fee quote failed");return sendError(res,error.code==="IDEMPOTENCY_CONFLICT"?409:400,error.code||"FEE_QUOTE_FAILED",error.message);}};
  app.post("/fees/quote",bearer(config),quoteHandler);
  app.post("/fees/calculate",bearer(config),quoteHandler);
  app.get("/fees/config",bearer(config),async(_q,res)=>{const value=await repo.getActiveConfig(pool);return value?sendOk(res,value):sendError(res,404,"FEE_CONFIG_NOT_FOUND","No active configuration");});
  app.post("/fees/config",bearer(config,"finance_admin"),async(req,res)=>{const parsed=configSchema.safeParse(req.body);if(!parsed.success)return sendError(res,400,"VALIDATION_ERROR","Invalid fee configuration");try{const value=await withTransaction(pool,async client=>{const result=await repo.createConfig(client,parsed.data,req.actor.id);await publishOutboxEvent(client,{event_type:"fees.config.changed",producer:"fee-service",correlation_id:req.correlationId,payload:{version:result.version,rule_count:result.rules.length}});await writeAudit(client,{actor_type:"admin",actor_id:req.actor.id,action:"fees.config.changed",resource_type:"fee_config",resource_id:result.id,result:"success",reason:parsed.data.reason,correlation_id:req.correlationId,request_id:req.requestId,after_metadata:{version:result.version,rule_count:result.rules.length}});return result;});return sendOk(res,value,201);}catch(error){logger.error({err:error,request_id:req.requestId},"fee config change failed");return sendError(res,400,"FEE_CONFIG_CHANGE_FAILED","Could not activate fee configuration");}});
  return{app,pool};}
module.exports={createApp,configSchema};
