const express = require("express"); const helmet = require("helmet"); const { z } = require("zod");
const { getConfig, createPool, createLogger, withTransaction, requestContext, sendOk, sendError, verifyAccessToken, writeAudit } = require("@wallet/common");
const repo = require("./repository"); const { render } = require("./templates"); const { MockEmailProvider, MockSmsProvider, MockPushProvider } = require("./providers");
const eventSchema = z.object({ event_id: z.string().uuid().optional(), event_type: z.enum(["user.registered","otp.requested","kyc.approved","kyc.rejected","wallet.created","transaction.successful","transaction.failed","withdrawal.pending","withdrawal.successful","fraud.case_created","account.suspended"]), user_id: z.string().uuid().optional(), payload: z.record(z.any()).default({}), correlation_id: z.string().uuid().optional() });
function auth(config) { return (req, res, next) => { const value = req.get("authorization") || ""; try { const token = value.startsWith("Bearer ") ? value.slice(7) : ""; req.actor = verifyAccessToken(config, token); next(); } catch (_e) { return sendError(res, 401, "UNAUTHORIZED", "Valid bearer token required"); } }; }
function channelsFor(eventType, preferences) { const security = ["otp.requested","fraud.case_created","account.suspended"].includes(eventType); const transaction = !security; return ["email","sms","push"].filter((channel) => preferences[`${channel}_enabled`] && (security ? preferences.security_enabled : transaction ? preferences.transaction_enabled : true)); }
function destination(channel, payload) { if (channel === "email") return payload.email || "masked-email"; if (channel === "sms") return payload.phone_e164 || payload.phone || "masked-phone"; return payload.push_token || "masked-push"; }
function createApp(deps = {}) {
  const config = deps.config || getConfig("notification-service"); const pool = deps.pool || createPool(config); const logger = deps.logger || createLogger("notification-service"); const providers = deps.providers || { email: new MockEmailProvider(), sms: new MockSmsProvider(), push: new MockPushProvider() }; const app = express();
  app.use(helmet()); app.use(express.json({ limit: "256kb" })); app.use(requestContext);
  app.get("/health/live", (_q, r) => r.json({ status: "ok" })); app.get("/health/ready", async (_q, r) => { try { await pool.query("SELECT 1"); r.json({ status: "ready" }); } catch (_e) { r.status(503).json({ status: "not_ready" }); } });
  async function deliver(client, notification, eventPayload) { const provider = providers[notification.channel]; try { const content = render(notification.event_type, eventPayload); const response = await provider.send({ notification_id: notification.id, destination: destination(notification.channel, eventPayload), subject: content.subject, body: content.body }); return repo.updateStatus(client, notification.id, "sent", { provider_name: notification.channel, provider_message_id: response.provider_message_id, next_retry_at: null }); } catch (error) { const attempts = Number(notification.attempt_count || 0) + 1; if (attempts >= (config.notificationMaxAttempts || 3)) return repo.deadLetter(client, notification, eventPayload, error.code || "DELIVERY_FAILED"); return repo.updateStatus(client, notification.id, "queued", { failure_reason: "Delivery failed; retry scheduled", failure_code: error.code || "DELIVERY_FAILED", next_retry_at: new Date(Date.now() + (config.notificationRetryDelayMs || 30000)) }); } }
  app.post("/events", auth(config), async (req, res) => { const parsed = eventSchema.safeParse(req.body); if (!parsed.success) return sendError(res, 400, "VALIDATION_ERROR", "Invalid event envelope"); try { const result = await withTransaction(pool, async (client) => { const preferences = await repo.preference(client, parsed.data.user_id); const channels = channelsFor(parsed.data.event_type, preferences); const notifications = []; for (const channel of channels) { const created = await repo.create(client, { user_id: parsed.data.user_id, event_id: parsed.data.event_id, event_type: parsed.data.event_type, template_code: parsed.data.event_type, channel, destination_masked: "masked", correlation_id: parsed.data.correlation_id, metadata: { source: "event" } }); const notification = created.repeated ? created.notification : await deliver(client, created.notification, parsed.data.payload); notifications.push(notification); if (!created.repeated) await writeAudit(client, { actor_type: "system", action: "notification.queued", resource_type: "notification", resource_id: notification.id, result: notification.status === "sent" ? "success" : "pending", correlation_id: parsed.data.correlation_id || req.correlationId, request_id: req.requestId, metadata: { event_type: parsed.data.event_type, channel, status: notification.status } }); } return notifications; }); return sendOk(res, { notifications: result }); } catch (error) { logger.warn({ err: error, request_id: req.requestId }, "notification event failed"); return sendError(res, 422, error.code || "NOTIFICATION_EVENT_FAILED", "Notification event could not be processed"); } });
  app.post("/notifications/:id/retry", auth(config), async (req, res) => { try { const result = await withTransaction(pool, async (client) => { const notification = await repo.get(client, req.params.id); if (!notification) return null; return deliver(client, notification, req.body.payload || {}); }); return result ? sendOk(res, result) : sendError(res, 404, "NOTIFICATION_NOT_FOUND", "Notification not found"); } catch (error) { return sendError(res, 422, "NOTIFICATION_RETRY_FAILED", "Notification retry failed"); } });
  app.get("/notifications", auth(config), async (req, res) => sendOk(res, { notifications: await repo.list(pool, req.actor.sub, Number(req.query.limit || 50)) }));
  app.get("/notifications/:id", auth(config), async (req, res) => { const result = await repo.get(pool, req.params.id); return result && result.user_id === req.actor.sub ? sendOk(res, result) : sendError(res, 404, "NOTIFICATION_NOT_FOUND", "Notification not found"); });
  app.get("/preferences", auth(config), async (req, res) => sendOk(res, await repo.preference(pool, req.actor.sub))); app.patch("/preferences", auth(config), async (req, res) => { const parsed = z.object({ email_enabled: z.boolean().optional(), sms_enabled: z.boolean().optional(), push_enabled: z.boolean().optional(), security_enabled: z.boolean().optional(), marketing_enabled: z.boolean().optional(), transaction_enabled: z.boolean().optional() }).safeParse(req.body); if (!parsed.success) return sendError(res, 400, "VALIDATION_ERROR", "Invalid preferences"); const result = await withTransaction(pool, (client) => repo.upsertPreference(client, req.actor.sub, parsed.data)); return sendOk(res, result); });
  return { app, pool, providers };
}
module.exports = { createApp, eventSchema, channelsFor };
