const { randomUUID } = require("crypto"); const { sha256 } = require("@wallet/common");
async function preference(client, userId) { const result = await client.query("SELECT * FROM notifications.preferences WHERE user_id=$1", [userId]); return result.rows[0] || { user_id: userId, email_enabled: true, sms_enabled: true, push_enabled: true, security_enabled: true, marketing_enabled: false, transaction_enabled: true }; }
async function upsertPreference(client, userId, input) { const result = await client.query(`INSERT INTO notifications.preferences(user_id,email_enabled,sms_enabled,push_enabled,security_enabled,marketing_enabled,transaction_enabled) VALUES ($1,COALESCE($2,true),COALESCE($3,true),COALESCE($4,true),COALESCE($5,true),COALESCE($6,false),COALESCE($7,true)) ON CONFLICT(user_id) DO UPDATE SET email_enabled=COALESCE($2,notifications.preferences.email_enabled),sms_enabled=COALESCE($3,notifications.preferences.sms_enabled),push_enabled=COALESCE($4,notifications.preferences.push_enabled),security_enabled=COALESCE($5,notifications.preferences.security_enabled),marketing_enabled=COALESCE($6,notifications.preferences.marketing_enabled),transaction_enabled=COALESCE($7,notifications.preferences.transaction_enabled),updated_at=now() RETURNING *`, [userId, input.email_enabled, input.sms_enabled, input.push_enabled, input.security_enabled, input.marketing_enabled, input.transaction_enabled]); return result.rows[0]; }
async function create(client, input) { const existing = await client.query("SELECT * FROM notifications.notifications WHERE event_id=$1 AND channel=$2 AND user_id=$3", [input.event_id || null, input.channel, input.user_id]); if (existing.rows[0]) return { notification: existing.rows[0], repeated: true }; const result = await client.query(`INSERT INTO notifications.notifications(id,user_id,channel,template_code,event_id,event_type,destination_masked,status,attempt_count,next_retry_at,correlation_id,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,'queued',0,now(),$8,$9) RETURNING *`, [randomUUID(), input.user_id || null, input.channel, input.template_code, input.event_id || null, input.event_type, input.destination_masked || "masked", input.correlation_id || null, input.metadata || {}]); return { notification: result.rows[0], repeated: false }; }
async function updateStatus(client, id, status, input = {}) { const result = await client.query(`UPDATE notifications.notifications SET status=$2,attempt_count=attempt_count+1,provider_name=COALESCE($3,provider_name),provider_reference=COALESCE($4,provider_reference),provider_message_id=COALESCE($5,provider_message_id),failure_reason=COALESCE($6,failure_reason),failure_code=COALESCE($7,failure_code),next_retry_at=$8,sent_at=CASE WHEN $2 IN ('sent','delivered') THEN now() ELSE sent_at END WHERE id=$1 RETURNING *`, [id, status, input.provider_name || null, input.provider_reference || null, input.provider_message_id || null, input.failure_reason || null, input.failure_code || null, input.next_retry_at || null]); return result.rows[0]; }
async function deadLetter(client, notification, payload, failureCode) { await client.query("INSERT INTO notifications.dead_letter_jobs(notification_id,event_id,event_type,channel,payload,failure_code,attempts) VALUES ($1,$2,$3,$4,$5,$6,$7)", [notification.id, notification.event_id, notification.event_type, notification.channel, payload || {}, failureCode, notification.attempt_count]); return updateStatus(client, notification.id, "undeliverable", { failure_code: failureCode }); }
async function get(client, id) { const result = await client.query("SELECT * FROM notifications.notifications WHERE id=$1", [id]); return result.rows[0] || null; }
async function list(client, userId, limit = 50) { const result = await client.query("SELECT * FROM notifications.notifications WHERE user_id=$1 ORDER BY queued_at DESC LIMIT $2", [userId, Math.min(limit, 100)]); return result.rows; }
module.exports = { preference, upsertPreference, create, updateStatus, deadLetter, get, list };
